/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package taktiktuk;

import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.border.*;

/**
 *
 * @author ucer
 */
public class game extends javax.swing.JFrame {
int x = 0;
boolean win = false;
int count=0;
    /**
     * Creates new form game
     */
    public game() {
        initComponents();
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        jMenuItem1 = new JMenuItem();
        jMenuItem2 = new JMenuItem();
        jMenu2 = new JMenu();
        jMenuItem3 = new JMenuItem();
        jPanel1 = new JPanel();
        b1 = new JButton();
        b3 = new JButton();
        b4 = new JButton();
        b2 = new JButton();
        b6 = new JButton();
        b5 = new JButton();
        b8 = new JButton();
        b7 = new JButton();
        b9 = new JButton();

        //======== this ========
        setDefaultCloseOperation(3);
        setTitle("Tak Tik Tuk");
        var contentPane = getContentPane();

        //======== jMenuBar1 ========
        {

            //======== jMenu1 ========
            {
                jMenu1.setText("File");

                //---- jMenuItem1 ----
                jMenuItem1.setText("New Game");
                jMenuItem1.addActionListener(e -> jMenuItem1ActionPerformed(e));
                jMenu1.add(jMenuItem1);

                //---- jMenuItem2 ----
                jMenuItem2.setText("Exit");
                jMenuItem2.addActionListener(e -> jMenuItem2ActionPerformed(e));
                jMenu1.add(jMenuItem2);
            }
            jMenuBar1.add(jMenu1);

            //======== jMenu2 ========
            {
                jMenu2.setText("About");
                jMenu2.addActionListener(e -> jMenu2ActionPerformed(e));

                //---- jMenuItem3 ----
                jMenuItem3.setText("About");
                jMenuItem3.addActionListener(e -> jMenuItem3ActionPerformed(e));
                jMenu2.add(jMenuItem3);
            }
            jMenuBar1.add(jMenu2);
        }
        setJMenuBar(jMenuBar1);

        //======== jPanel1 ========
        {
            jPanel1.setBorder(LineBorder.createBlackLineBorder());
            jPanel1.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EmptyBorder
            (0,0,0,0), "JF\u006frmD\u0065sig\u006eer \u0045val\u0075ati\u006fn",javax.swing.border.TitledBorder.CENTER,javax.swing.border
            .TitledBorder.BOTTOM,new java.awt.Font("Dia\u006cog",java.awt.Font.BOLD,12),java.awt
            .Color.red),jPanel1. getBorder()));jPanel1. addPropertyChangeListener(new java.beans.PropertyChangeListener(){@Override public void
            propertyChange(java.beans.PropertyChangeEvent e){if("\u0062ord\u0065r".equals(e.getPropertyName()))throw new RuntimeException()
            ;}});

            //---- b1 ----
            b1.setBorder(new BevelBorder(BevelBorder.RAISED));
            b1.addActionListener(e -> b1ActionPerformed(e));

            //---- b3 ----
            b3.setBorder(new BevelBorder(BevelBorder.RAISED));
            b3.addActionListener(e -> b3ActionPerformed(e));

            //---- b4 ----
            b4.setBorder(new BevelBorder(BevelBorder.RAISED));
            b4.addActionListener(e -> b4ActionPerformed(e));

            //---- b2 ----
            b2.setBorder(new BevelBorder(BevelBorder.RAISED));
            b2.addActionListener(e -> b2ActionPerformed(e));

            //---- b6 ----
            b6.setBorder(new BevelBorder(BevelBorder.RAISED));
            b6.addActionListener(e -> b6ActionPerformed(e));

            //---- b5 ----
            b5.setBorder(new BevelBorder(BevelBorder.RAISED));
            b5.addActionListener(e -> b5ActionPerformed(e));

            //---- b8 ----
            b8.setBorder(new BevelBorder(BevelBorder.RAISED));
            b8.addActionListener(e -> b8ActionPerformed(e));

            //---- b7 ----
            b7.setBorder(new BevelBorder(BevelBorder.RAISED));
            b7.addActionListener(e -> b7ActionPerformed(e));

            //---- b9 ----
            b9.setBorder(new BevelBorder(BevelBorder.RAISED));
            b9.addActionListener(e -> b9ActionPerformed(e));

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b4, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b7, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b8, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b9, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b1, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(b1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addComponent(b6, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(b4, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addComponent(b5, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(b8, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(26, 26, 26))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanel1.setVisible(true);
         b1.setText(null);b2.setText(null);b3.setText(null);b4.setText(null);
         b5.setText(null); b6.setText(null); b7.setText(null); b8.setText(null); b9.setText(null); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(x==0){
        b2.setText("0");
        x=1;
        }else{
        b2.setText("x");
        x=0;
        }count++;
        checkwin();
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
         if(x==0){
        b1.setText("0");
        x=1;
        }else{
        b1.setText("x");
        x=0;
        }count++;
          checkwin();
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
         if(x==0){
        b3.setText("0");
        x=1;
        }else{
        b3.setText("x");
        x=0;
        }count++;
          checkwin();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(x==0){
        b4.setText("0");
        x=1;
        }else{
        b4.setText("x");
        x=0;
        }count++;
         checkwin();
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
         if(x==0){
        b5.setText("0");
        x=1;
        }else{
        b5.setText("x");
        x=0;
        }count++;
          checkwin();
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
         if(x==0){
        b6.setText("0");
        x=1;
        }else{
        b6.setText("x");
        x=0;
        }count++;
          checkwin();
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
         if(x==0){
        b7.setText("0");
        x=1;
        }else{
        b7.setText("x");
        x=0;
        }count++;
          checkwin();
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(x==0){
        b8.setText("0");
        x=1;
        }else{
        b8.setText("x");
        x=0;
        }count++;
         checkwin();
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(x==0){
        b9.setText("0");
        x=1;
        }else{
        b9.setText("x");
        x=0;
        }count++;
         checkwin();
    }//GEN-LAST:event_b9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int y = JOptionPane.showConfirmDialog(this, "Are you sure that you want to exit", "Exit Game", JOptionPane.YES_NO_OPTION);
        if(y==JOptionPane.YES_OPTION){System.exit(0);}
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
      
 
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       JOptionPane.showMessageDialog(this, "This game can be played by two players \n you can win the game if you able to \n arrange three '0' or 'x' vertically,horizontally or diagonally.", "About this Game", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
void checkwin(){
 
     if(("0".equals(b1.getText())&& "0".equals(b2.getText())&& "0".equals(b3.getText()))
             ||("0".equals(b4.getText())&&"0".equals(b5.getText())&& "0".equals(b6.getText()))
             ||("0".equals(b7.getText())&& "0".equals(b8.getText())&& "0".equals(b9.getText()))
                ||("0".equals(b1.getText())&& "0".equals(b4.getText())&& "0".equals(b7.getText()))
                ||("0".equals(b2.getText())&& "0".equals(b5.getText())&& "0".equals(b8.getText()))
                ||("0".equals(b3.getText())&& "0".equals(b6.getText())&& "0".equals(b9.getText()))
                    ||("0".equals(b1.getText())&& "0".equals(b5.getText())&& "0".equals(b9.getText()))
                    ||("0".equals(b3.getText())&& "0".equals(b5.getText())&& "0".equals(b7.getText()))){
        win = true;
         JOptionPane.showMessageDialog(this, " 0 won the game");
     b1.setText(null); b2.setText(null); b3.setText(null); b4.setText(null);
     b5.setText(null); b6.setText(null); b7.setText(null); b8.setText(null); b9.setText(null);
     } else if(("x".equals(b1.getText())&& "x".equals(b2.getText())&& "x".equals(b3.getText()))
             ||("x".equals(b4.getText())&& "x".equals(b5.getText())&& "x".equals(b6.getText()))
             ||("x".equals(b7.getText())&& "x".equals(b8.getText())&& "x".equals(b9.getText()))
                ||("x".equals(b1.getText())&& "x".equals(b4.getText())&& "x".equals(b7.getText()))
                ||("x".equals(b2.getText())&& "x".equals(b5.getText())&& "x".equals(b8.getText()))
                ||("x".equals(b3.getText())&& "x".equals(b6.getText())&& "x".equals(b9.getText()))
                    ||("x".equals(b1.getText())&& "x".equals(b5.getText())&& "x".equals(b9.getText()))
                    ||("x".equals(b3.getText())&& "x".equals(b5.getText())&& "x".equals(b7.getText()))){
        win = true; 
         JOptionPane.showMessageDialog(this, " X won the game");
     b1.setText(null); b2.setText(null); b3.setText(null); b4.setText(null);
     b5.setText(null); b6.setText(null); b7.setText(null); b8.setText(null); b9.setText(null); 
     }else if(count==9&&win==false){
          JOptionPane.showMessageDialog(this,"tie game!");
          }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JMenuBar jMenuBar1;
    private JMenu jMenu1;
    private JMenuItem jMenuItem1;
    private JMenuItem jMenuItem2;
    private JMenu jMenu2;
    private JMenuItem jMenuItem3;
    private JPanel jPanel1;
    private JButton b1;
    private JButton b3;
    private JButton b4;
    private JButton b2;
    private JButton b6;
    private JButton b5;
    private JButton b8;
    private JButton b7;
    private JButton b9;
    // End of variables declaration//GEN-END:variables
}
